[deploy]
bucket = 'cfn-artifacts-ganeshpondy'
region = 'ap-south-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:ap-south-1:387543059434:certificate/3c49f37a-a67c-43a4-adb0-53e38d8892dd'